### ISSUE TITLE
Header/footer in TAB sometimes doesn't display in 1.13.1

### ISSUE THREAD

**Issue by pop4959** [Puharesource/TitleManager#189]
I'm not sure what else to say other than what's in the title. It sometimes loads on startup, and sometimes doesn't. If it does, it usually disappears after some time. I already reported this on the spigot resource discussion page, and a few other people have mentioned the same difficulties.

**Comment by BBoyJD10** [comment]
Same here

**Comment by xion87** [comment]
I Confirm the issue with 1.12.2 version, no issue with 1.8.8 server, downgrading to version 2.0.9 fix the issue on 1.12.2 server

**Comment by Puharesource** [comment]
Sorry for the response time, I've been quite busy lately.

I should have time to produce a fix within the week.

**Comment by BBoyJD10** [comment]
Any news?

**Comment by mattboy9921** [comment]
Glad to see this is fixed, can't wait for a new release with this. Thanks!

**Comment by xion87** [comment]
the bug is still here 
![image](https://user-images.githubusercontent.com/3611852/67125576-6bd65180-f1f5-11e9-86ff-d115cb20d549.png)

**Comment by pop4959** [comment]
Nice necro @xion87

I will also go ahead and add that (with no disrespect towards @Puharesource) I no longer actually use this plugin because of this issue. Instead, I have my own plugin in which I use [this API method](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#setPlayerListHeaderFooter-java.lang.String-java.lang.String-) which works perfectly. I believe TitleManager used/has used NMS for this, but I think if it switched to using the recent API methods it would work much more compatibly.

**Comment by Puharesource** [comment]
Thanks @pop4959 I haven't been writing plugins for Minecraft for a long time, I don't really know when new API functionality is introduced, I'll implement this in the future.

**Comment by martinambrus** [comment]
> 
> 
> Nice necro @xion87
> 
> I will also go ahead and add that (with no disrespect towards @Puharesource) I no longer actually use this plugin because of this issue. Instead, I have my own plugin in which I use [this API method](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#setPlayerListHeaderFooter-java.lang.String-java.lang.String-) which works perfectly. I believe TitleManager used/has used NMS for this, but I think if it switched to using the recent API methods it would work much more compatibly.

Is your plugin publicly available? It would help the community a lot if it was, since this issue is what's keeping a lot of people from using TitleManager.
