### ISSUE TITLE
Client Error when logging in

### ISSUE THREAD

**Issue by SirKillian** [Puharesource/TitleManager#308]
**Describe the bug**
Client error when player logs in.

**To Reproduce**
1. Log in with client side logging enabled (just so you can see the error)

**Expected behavior**
I'd expect no error client side.

**Screenshots**
![](https://sirkillian.gg/i/ypbwowazeziokcih.png)

**Stacktrace / Error**
This is not a server error, this is an error on the client.
https://pastebin.com/hGG9JFri

**Server information:**
 - TitleManager version: 2.3.1
 - Spigot version: Tuinity 1.16.4

**Comment by Puharesource** [comment]
Fixed in 7e1f576ab15b1d7009c0ca89edc96864a4741ea4

**Comment by SirKillian** [comment]
Still happening in 2.3.3
[Pastebin](https://pastebin.com/8eJ8HEnP)
