### ISSUE TITLE
TitleManager placeholders format conflicts with Placerholder api

### ISSUE THREAD

**Issue by Blackyvk** [Puharesource/TitleManager#91]
I was testing the 2.0.0-Pre5 and there is a problem with placeholders...

the placeholders-api work fine if you use %player_name%  for example but

the placeholders from your own plugin they dont work unless you write %{balance}, so every placeholder from placeholderapi stops working because of it you need to close that with another % 

so i made something like this to make it work
(footer)
  - '&e&lOnline: &e%{safe-online}%&8/&6100'   <titlemanager placeholder
  - '&e&lPoints: &7%playerpoints_points%'    < placeholder api
  - '&2Balance: &3%vault_eco_balance_formatted%'     < placeholder api

 So i guess it needs to be fixed, because the second % from the first line appears visible in the tablist

**Comment by Puharesource** [comment]
Thanks for the bug report, though I'm a bit confused as to how the issue is occurring.

What happens if you remove the last % from %{safe-online}, will placeholder api give you issues? Or what's happening?

**Comment by Blackyvk** [comment]
yes, the placeholdersapi show as %playerpoints_points% not giving the info it should...

**Comment by Puharesource** [comment]
This seems to be an issue with PlaceholderAPI and the regex used.
I've already contacted @extendedclip on Skype as he doesn't seem to active on GitHub.

The regex in question is found here: https://github.com/extendedclip/PlaceholderAPI/blob/master/src/me/clip/placeholderapi/PlaceholderAPI.java#L24

and should be changed from:
`[%]([^%]+)[%]` to `[%]([^% ]+)[%]`

It's as simple as adding a space, this can be done for the other format as well.

**Comment by extendedclip** [comment]
I will push an update to PlaceholderAPI tomorrow with a fix regarding this issue.

**Comment by extendedclip** [comment]
After thinking about it a bit while here at work, does TitleManager parse it's placeholders after placeholderapi? If so why not just switch it to allow TitleManager handles it's own placeholder parsing before you hand the string off to placeholderapi? My main concern is there may be a plugin that utilizes the space character within a placeholder although I do not use spaces myself. Ignoring the space character may break compatibility with a plugin that adds placeholders to papi.

**Comment by Puharesource** [comment]
Yeah, I should probably just change the order in which it replaces, I can't believe I didn't think about that >.<. Though you should probably make a way for someone to be able to have percentages without messing with all of the placeholders. Maybe as simple as ` \%` ?

**Comment by Puharesource** [comment]
@Blackyvk The issue has been fixed, here's the fixed pre-release https://github.com/Puharesource/TitleManager/releases/tag/2.0.0-7

**Comment by ozzie1507** [comment]
but on the pre releas is no scoreboard

**Comment by olliegardner** [comment]
This still doesn't seem to be fixed. What is the correct format for using custom placeholders from the PlaceholderAPI?

**Comment by Puharesource** [comment]
@olliegardner `%myplaceholder%` If you have a % somewhere in your text, the placeholders won't work, if you want a fix for this, you'll have to talk to Clip (the developer of PlaceholderAPI)
